mysite/accounts/urls.py
from django.urls import path
from .views import SignUpView, SignUpSuccessView
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'accounts'
urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signup_success/', SignUpSuccessView.as_view(), name='signup_success'),
    path('login/', LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('entryapp.urls')),
    path('', include('accounts.urls')),
]

mysite/entryapp/urls.py
from django.urls import path
from .views import ListEntryView, DetailEntryView, CreateEntryView, UserView

app_name = 'entryapp'
urlpatterns = [
    # path('', views.hello_world, name='index'),
    path('entries/', ListEntryView.as_view(), name='entry_list'),
    path('entry/<int:pk>/detail/', DetailEntryView.as_view(), name='detail_entry'),
    path('entry/create/', CreateEntryView.as_view(), name='create_entry'),
    path('user/<int:user>/entries/', UserView.as_view(), name='user_list'),
]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

mysite/entryapp/models.py
from django.db import models
from accounts.models import CustomUser


class EntryModel(models.Model):
    title = models.CharField(max_length=50)
    entry_text = models.CharField(max_length=500)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

mysite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'email', 'password1', 'password2')
      

mysite/accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView, TemplateView
from django.urls import reverse_lazy

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('accounts:signup_success')

    def form_valid(self, form):
        user = form.save()
        self.object = user
        return super().form_valid(form)

class SignUpSuccessView(TemplateView):
    template_name = 'accounts/signup_success.html'

mysite/entryapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import EntryModel


def hello_world(request):
    return HttpResponse("Hello, world. You're at the entryapp index.")

class ListEntryView(LoginRequiredMixin, ListView):
    template_name = 'entry/entrymodel_list.html'
    model = EntryModel

class DetailEntryView(LoginRequiredMixin, DetailView):
    template_name = 'entry/entry_detail.html'
    model = EntryModel

class CreateEntryView(LoginRequiredMixin, CreateView):
    template_name = 'entry/entry_create.html'
    model = EntryModel
    fields = ['title', 'entry_text']
    success_url = reverse_lazy('entryapp:entry_list')

    def form_valid(self, form):
        entry = form.save(commit=False)
        entry.user = self.request.user
        entry.save()
        return super().form_valid(form)

class UserView(LoginRequiredMixin, ListView):
    template_name = 'entry/entrymodel_list.html'
    paginate_by = 9

    def get_queryset(self):
        user_id = self.kwargs['user']
        user_list = EntryModel.objects.filter(
            user=user_id
        )
        return user_list

mysite/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if form.errors %}
    <p style="color: red">ユーザー名とパスワードが一致しません。</p>
    {% endif %}
    {% if user.is_authenticated %}
    <h2>すでにログインしています。</h2>
    {% else %}
    <form method="post">
        {% csrf_token %}
        <h1>ログインページ</h1>

        <label for="Username">User name</label>
        <input type="text" name="username" id="id_username"><br>
        <label for="Password">Password</label>
        <input type="password" name="password" id="id_password"><br>

        <input type="submit" value="ログイン">
    </form>
    {% endif %}
</body>
</html>

mysite/templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ログアウト</title>
</head>
<body>
    <h3>ログアウトしました</h3>
    <a href="{% url 'accounts:login' %}">ログインページ</a>
</body>
</html>

mysite/templates/accounts/signup.html
{% extends "base.html" %}
{% block content %}
<h2>Sign up</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.label_tag }}<br>
        {{ field }}
    </div>
    {% for error in field.errors %}
    <p style="color:red">{{ error }}</p>
    {% endfor %}
    {% endfor %}
    <input type="submit" values="Sign up">
</form>
{% endblock %}

mysite/templates/accounts/signup_success.html
{% extends "base.html" %}
{% block content %}
<h2>ユーザー登録完了しました。</h2>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>title</title>
</head>
<body>
    {% block content %}{% endblock %}
    <a href="{% url 'accounts:logout' %}">ログアウト</a>
</body>
</html>

mysite/templates/entry/entry_create.html
{% extends "base.html" %}
{% block content %}
<h2>Register</h2>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
    <div>
        {{ field.label_tag}}<br>
        {{ field }}
    </div>
    {% for error in field.errors %}
    <p style="color: red">{{ error }}</p>
    {% endfor %}
    {% endfor %}
    <input type="submit" value="Sign up">
</form>
{% endblock %}

mysite/templates/entry/entry_detail.html
{% extends "base.html" %}
{% block content %}
    <h2>{{ object.title }}</h2>
    <p>{{ object.entry_text }}</p>
    <a href="{% url 'entryapp:entry_list' %}">戻る</a>
{% endblock %}

mysite/templates/entry/entrymodel_list.html
{% extends "base.html" %}

{% block content %}
{% for entry in object_list %}
<ul>
    <li>{{ entry.title }}</li>
    <a href="{% url 'entryapp:detail_entry' entry.pk %}">詳細はこちら</a>
</ul>
{% endfor %}
{% endblock %}